apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2020-07-28T11:53:12Z"
    cni.projectcalico.org/podIP: 10.42.3.34/32
    cpaas.io/creator: u-g26pf
    field.cattle.io/ports: '[[{"containerPort":2444,"dnsName":"xo-","name":"fileserver","protocol":"TCP","sourcePort":0},{"containerPort":2333,"dnsName":"xo-","name":"http","protocol":"TCP","sourcePort":0},{"containerPort":2222,"dnsName":"xo-","name":"ws","protocol":"TCP","sourcePort":0}]]'
  creationTimestamp: "2020-09-02T08:19:40Z"
  generateName: xo-848f99547b-
  labels:
    app: xo
    pod-template-hash: 848f99547b
  name: xo-848f99547b-r98wc
  namespace: xshrim
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: xo-848f99547b
    uid: ea0e4cdb-d0c8-11ea-9815-fa163e1f29db
  resourceVersion: "179935740"
  selfLink: /api/v1/namespaces/xshrim/pods/xo-848f99547b-r98wc
  uid: 0c4ef3a9-ecf5-11ea-92e6-fa163e1f29db
spec:
  containers:
  - env:
    - name: HOST
      value: 25.2.20.2
    - name: HSDIR
      value: /share
    - name: HSPASSWD
      value: Transfer@123
    - name: HSUSER
      value: admin
    - name: PASSWD
      value: abcde@123
    - name: PORT
      value: "16022"
    - name: SSL
      value: "true"
    - name: TIMEOUT
      value: "600"
    - name: USER
      value: root
    - name: WEBHOST
      value: share.ebcpaas.com
    image: xo
    imagePullPolicy: Always
    name: xo
    ports:
    - containerPort: 2444
      name: fileserver
      protocol: TCP
    - containerPort: 2333
      name: http
      protocol: TCP
    - containerPort: 2222
      name: ws
      protocol: TCP
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 200m
        memory: 128Mi
    securityContext:
      capabilities: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /share
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-s78pd
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: dockercfg--test--test-harbor
  nodeName: region2-worker03
  nodeSelector:
    app: ebtech.paas
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: data
    nfs:
      path: /ebcpass_baas_daw__01_nfs/share
      server: 25.14.1.1
  - name: default-token-s78pd
    secret:
      defaultMode: 420
      secretName: default-token-s78pd
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-09-02T08:19:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-09-02T08:19:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-09-02T08:19:43Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-09-02T08:19:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://cea49505b5afcc15327d73d13069a5929a2ce8fecff57a7df31087919477d52a
    image: xo:latest
    imageID: docker-pullable://xo@sha256:eaf698b61ee7391c27bb771b988adf4f2c7277f4d8c605690d615cddb34c3492
    lastState:
      terminated:
        containerID: docker://f3222ad44778be483a4588cdee53d23c3551e3663d717ac81792b743360a6943
        exitCode: 137
        finishedAt: "2020-09-02T08:24:33Z"
        reason: OOMKilled
        startedAt: "2020-09-02T08:19:42Z"
    name: xo
    ready: true
    restartCount: 1
    state:
      running:
        startedAt: "2020-09-02T08:24:34Z"
  hostIP: 25.2.20.8
  phase: Running
  podIP: 10.42.3.34
  qosClass: Guaranteed
  startTime: "2020-09-02T08:19:40Z"



|yq d - status|yq d - metadata.ownerReferences|yq d - metadata.managedFields|yq d - metadata.creationTimestamp|yq d - metadata.generation|yq d - metadata.generateName|yq d - metadata.resourceVersion|yq d - metadata.selfLink |yq d - metadata.uid|yq d - spec.template.metadata.creationTimestamp|grep -v 'progressDeadlineSeconds: 600'|grep -v 'revisionHistoryLimit: 10'|grep -v 'dnsPolicy: ClusterFirst'|grep -v 'dnsConfig: {}'|grep -v 'enableServiceLinks: true'|grep -v 'priority: 0'|grep -v 'restartPolicy: Always'|grep -v 'schedulerName: default-scheduler'|grep -v 'securityContext: {}'|grep -v 'serviceAccount: default'|grep -v 'serviceAccountName: default'|grep -v 'terminationGracePeriodSeconds: 30'|grep -v 'terminationMessagePath: /dev/termination-log'|grep -v 'terminationMessagePolicy: File'|grep -v 'imagePullPolicy: IfNotPresent'|grep -v 'resources: {}'|grep -v 'stdin: true'|grep -v 'tty: true'


|yq d - items.*.status|yq d - items.*.metadata.ownerReferences|yq d - items.*.metadata.managedFields|yq d - items.*.metadata.creationTimestamp|yq d - items.*.metadata.generation|yq d - items.*.metadata.generateName|yq d - items.*.metadata.resourceVersion|yq d - items.*.metadata.selfLink |yq d - items.*.metadata.uid|yq d - items.*.spec.template.metadata.creationTimestamp|yq d - status|yq d - metadata.ownerReferences|yq d - metadata.managedFields|yq d - metadata.creationTimestamp|yq d - metadata.generation|yq d - metadata.generateName|yq d - metadata.resourceVersion|yq d - metadata.selfLink |yq d - metadata.uid|yq d - spec.template.metadata.creationTimestamp|grep -v 'progressDeadlineSeconds: 600'|grep -v 'revisionHistoryLimit: 10'|grep -v 'dnsPolicy: ClusterFirst'|grep -v 'dnsConfig: {}'|grep -v 'enableServiceLinks: true'|grep -v 'priority: 0'|grep -v 'restartPolicy: Always'|grep -v 'schedulerName: default-scheduler'|grep -v 'securityContext: {}'|grep -v 'serviceAccount: default'|grep -v 'serviceAccountName: default'|grep -v 'terminationGracePeriodSeconds: 30'|grep -v 'terminationMessagePath: /dev/termination-log'|grep -v 'terminationMessagePolicy: File'|grep -v 'imagePullPolicy: IfNotPresent'|grep -v 'resources: {}'|grep -v 'stdin: true'|grep -v 'tty: true'


jq -r 'del(.status)'|jq -r 'del(.metadata.ownerReferences)'|jq -r 'del(.metadata.managedFields)'|jq -r 'del(.metadata.creationTimestamp)'|jq -r 'del(.metadata.generation)'|jq -r 'del(.metadata.generateName)'|jq -r 'del(.metadata.resourceVersion)'|jq -r 'del(.metadata.selfLink)'|jq -r 'del(.metadata.uid)'|jq -r 'del(.spec.template.metadata.creationTimestamp)'|grep -v '"progressDeadlineSeconds": 600'|grep -v '"revisionHistoryLimit": 10'|grep -v '"dnsPolicy": "ClusterFirst"'|grep -v '"dnsConfig": {}'|grep -v '"enableServiceLinks": true'|grep -v '"priority": 0'|grep -v '"restartPolicy": "Always"'|grep -v '"schedulerName": "default-scheduler"'|grep -v '"securityContext": {}'|grep -v '"serviceAccount": "default"'|grep -v '"serviceAccountName": "default"'|grep -v '"terminationGracePeriodSeconds": 30'|grep -v '"terminationMessagePath": "/dev/termination-log"'|grep -v '"terminationMessagePolicy": "File"'|grep -v '"imagePullPolicy": "IfNotPresent"'|grep -v '"resources": {}'|grep -v '"stdin": true'|grep -v '"tty": true'