#!/bin/bash

# Calculate where the image should be placed on the screen.
num="$(printf "%0.f\n" "$(echo "$(tput cols) / 2" | bc)")"
numb="$(printf "%0.f\n" "$(echo "$(tput cols) - $num - 1" | bc)")"
numc="$(printf "%0.f\n" "$(echo "$(tput lines) - 2" | bc)")"

image() {
	if [ -n "$DISPLAY" ]; then
		declare -p -A cmd=([action]=add [identifier]="PREVIEW" [x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5" [path]="$1") > "$FIFO_UEBERZUG"
		exit 1
	else
		chafa "$1" -s "${4}x${5}"
	fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

h() {
  if type highlight &>/dev/null; then
    highlight -D /home/xshrim/.oh-my-zsh/custom/plugins/comm/highlight -O xterm256 -t 4 -s bipolar $@ 2>/dev/null || highlight -D /home/xshrim/.oh-my-zsh/custom/plugins/comm/highlight -S sh -O xterm256 -t 4 -s bipolar $@ 2>/dev/null || \cat $@
  fi
}

case "$(echo "$1" | awk '{print tolower($0)}')" in
*.tar*) tar tvf "$1" ;;
*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
*.rar) unrar l "$1" ;;
*.7z) 7z l "$1" ;;
*.deb) ar -tOv "$1" ;;
*.rpm) rpm -qpvl "$1" ;;
*.pdf) pdftotext "$1" - ;;
*.[1-8]) man "$1" | col -b ;;
*.o) nm "$1" | less ;;
*.torrent) transmission-show "$1" ;;
*.iso) iso-info --no-header -l "$1" ;;
*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
*.doc) catdoc "$1" ;;
*.docx) docx2txt "$1" - ;;
*.xls) xls2csv "$1" ;;
*.xlsx) xlsx2csv "$1" ;;
*.csv) h "$1" ;;
*.json) jq --color-output "$1" ;;
*.htm|*.html|*.xhtml) w3m -dump "$1" ;;
*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp)
  image "$1" "$num" 1 "$numb" "$numc"
  ;;
*.wav|*.dff|*.dsf|*.wv|*.wvc|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx])
  mediainfo "$1"
  ;;
*.otf|*.ttf|*.ttc)
	[ ! -f "${CACHE}.jpg" ] && fontpreview -i "$1" -o "${CACHE}.jpg"
  image "${CACHE}.jpg" "$num" 1 "$numb" "$numc"
  ;;
*.pdf)
  [ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
  image "${CACHE}.jpg" "$num" 1 "$numb" "$numc"
  ;;
*.epub)
  [ ! -f "$CACHE" ] && epub-thumbnailer "$1" "$CACHE" 1024
  image "$CACHE" "$num" 1 "$numb" "$numc"
  ;;
*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
  [ ! -f "${CACHE}.jpg" ] && ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
  image "${CACHE}.jpg" "$num" 1 "$numb" "$numc"
  ;;
*) h "$1" ;;
esac
