#!/bin/bash

# Calculate where the image should be placed on the screen.
num="$(printf "%0.f\n" "$(echo "$(tput cols) / 2" | bc)")"
numb="$(printf "%0.f\n" "$(echo "$(tput cols) - $num - 1" | bc)")"
numc="$(printf "%0.f\n" "$(echo "$(tput lines) - 2" | bc)")"

text() {
  mime=$(file --dereference --mime-type -b "$*")
  case "$mime" in
    text/*)
      if type highlight &>/dev/null; then
        highlight -O xterm256 -t 4 -s bipolar --force "$*"
      elif type bat &>/dev/null; then
        bat -Pp "$*"
      elif type ccat &>/dev/null; then
        ccat "$*"
      else
        cat "$*"
      fi
      ;;
    *)
      echo "--- File Type Classification ---"
      echo ""
      file -b "$*" | fold -s
      echo ""
      stat "$*"
      ;;
  esac
}

image() {
	if [ -n "$DISPLAY" ]; then
		declare -p -A cmd=([action]=add [identifier]="PREVIEW" [x]="$2" [y]="$3" [max_width]="$4" [max_height]="$5" [path]="$1") > "$FIFO_UEBERZUG"
		exit 1
	else
		chafa "$1" -s "${4}x${5}"
    #feh "$1"
	fi
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"
TREE=$(type tree &>/dev/null && echo "tree --fromfile -C" || echo "cat")

case "$(echo "$1" | awk '{print tolower($0)}')" in
*.tar|*.tar.gz|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz) tar tf "$1" | $TREE;;
*.zip|*.jar|*.apk|*.war|*.ear|*.oxt) unzip -l "$1" | awk 'NR>3 {print $4}' | sed '/^$/d' | $TREE;;
*.rar) unrar lb "$1" | $TREE;;
*.7z) 7z l "$1" | sed -n '/^---/,/^---/p' | sed '1d;$d' | cut -c 53- | sed 's/^[[:space:]]*//' | $TREE;;
#*.deb) ar -tOv "$1" | $TREE;;
*.deb) dpkg -c "$1" | awk '{print $6}' | sed 's/^\.//' | $TREE;;
*.rpm) rpm -qpl "$1" 2>/dev/null | $TREE;;
*.pdf) pdftotext "$1" - ;;
*.[1-8]) man "$1" | col -b ;;
*.o) nm "$1" | less ;;
*.torrent) transmission-show "$1" ;;
*.iso) iso-info --no-header -l "$1" ;;
*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
*.doc) catdoc "$1" ;;
*.docx) docx2txt "$1" - ;;
*.xls) xls2csv "$1" ;;
*.xlsx) xlsx2csv "$1" ;;
*.csv) text "$1" ;;
*.json) jq --color-output "$1" ;;
*.htm|*.html|*.xhtml) w3m -dump "$1" ;;
*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp) image "$1" "$num" 1 "$numb" "$numc";;
#*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp) feh "$1";;
*.wav|*.dff|*.dsf|*.wv|*.wvc|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx])
  mediainfo "$1"
  ;;
*.otf|*.ttf|*.ttc)
	[ ! -f "${CACHE}.jpg" ] && fontpreview -i "$1" -o "${CACHE}.jpg"
  image "${CACHE}.jpg" "$num" 1 "$numb" "$numc"
  #feh "${CACHE}.jpg"
  ;;
*.pdf)
  [ ! -f "${CACHE}.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
  image "${CACHE}.jpg" "$num" 1 "$numb" "$numc"
  #feh "${CACHE}.jpg"
  ;;
*.epub)
  [ ! -f "$CACHE" ] && epub-thumbnailer "$1" "$CACHE" 1024
  image "$CACHE" "$num" 1 "$numb" "$numc"
  #feh "$CACHE"
  ;;
*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
  [ ! -f "${CACHE}.jpg" ] && ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
  image "${CACHE}.jpg" "$num" 1 "$numb" "$numc"
  #feh "${CACHE}.jpg"
  ;;
*) text "$1" ;;
esac
